### ISSUE TITLE
Unable To Install

### ISSUE THREAD

**Issue by ghost** [ticktackk/hCaptchaIntegrationForXF2#2]
**Installation Error**
![image](https://user-images.githubusercontent.com/16944217/79853775-27f51c80-83d1-11ea-9589-66d2e640adf7.png)

**Server Information**
![image](https://user-images.githubusercontent.com/16944217/79853814-35aaa200-83d1-11ea-8793-d5d1aff305b5.png)

**XenForo Version**
v2.1.8 Patch 2

**Comment by ticktackk** [comment]
This add-on follows `TickTackk\hCaptchaIntegration` namespace and for setup the class name `TickTackk\hCaptchaIntegration\Setup` must be . Not sure how you have got `HCAPTCHA\Setup`.

Make sure you have downloaded the right add-on files.

**Comment by ghost** [comment]
Yes, followed your instructions now. Seems right, but that was not mentioned anywhere.

I'm facing this issue now - 
![image](https://user-images.githubusercontent.com/16944217/79882837-dc0b9d00-83fb-11ea-902b-98d556cf6440.png)

I've gone ahead to install anyways but this still seems like an important thing to have because it can not tell if the Addon has corrupted files or not.

**Comment by ghost** [comment]
Quick follow up, I'm not seeing hCaptcha as an option within the captcha selections. Am I looking in the wrong place?

**Comment by ticktackk** [comment]
@danielnaaman This repository is to manage the add-on source code. If you want to get the installable add-on file then you must get it from the [releases](https://github.com/ticktackk/hCaptchaIntegrationForXF2/releases) page.

![image](https://user-images.githubusercontent.com/31729605/79883140-2b0ffd00-8411-11ea-9b1b-1ef91144a0b1.png)

**Comment by ghost** [comment]
I most certainly feel like an idiot know, should have checked for releases first.

Thank you for your assistance.

Good day.
